name: "Tests"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron: '36 13 * * 5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}

jobs:
  tests:
    uses: "SciML/.github/.github/workflows/grouped-tests.yml@v1"
    secrets: "inherit"
  tests-32bit:
    name: "Core (julia 1, ubuntu-latest, x86)"
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "1"
      julia-arch: "x86"
      group: "Core"
      coverage: false
    secrets: "inherit"
